/**
 * Seed curriculum catalog.
 *
 * Standards references are informative alignments to help parents keep
 * records (Common Core ELA/Math, NGSS performance expectations and DCIs,
 * National Core Arts Standards, CASEL SEL competencies, Head Start ELOF).
 * They are never shown to the child.
 */
import type { Difficulty, Domain, DomainId, Skill, StandardRef, Strand } from './types';

export const DOMAINS: Domain[] = [
  {
    id: 'reading',
    name: 'Reading',
    childName: 'Story Adventures',
    color: '#c8553d',
    primary: true,
    description: 'Decoding, fluency, comprehension, narration and a love of books.',
  },
  {
    id: 'math',
    name: 'Mathematics',
    childName: 'Number Quests',
    color: '#2f7f8a',
    primary: true,
    description: 'Counting, operations, measurement, geometry and mathematical reasoning.',
  },
  {
    id: 'science',
    name: 'Science',
    childName: 'Discovery Lab',
    color: '#5f8f4e',
    primary: true,
    description: 'Scientific practices, life, physical, and earth & space science.',
  },
  {
    id: 'writing',
    name: 'Writing',
    childName: 'Word Workshop',
    color: '#8a5a9e',
    primary: false,
    description: 'Handwriting, spelling, and composing through drawing, dictation and writing.',
  },
  {
    id: 'vocabulary',
    name: 'Vocabulary',
    childName: 'Word Treasures',
    color: '#b8862f',
    primary: false,
    description: 'Rich language, word relationships, and learning words from context.',
  },
  {
    id: 'reasoning',
    name: 'Reasoning',
    childName: 'Puzzle Power',
    color: '#4a6fa5',
    primary: false,
    description: 'Sequencing, classification, cause and effect, and persistent problem solving.',
  },
  {
    id: 'lifeSkills',
    name: 'Life Skills',
    childName: 'Helping Hands',
    color: '#c7773a',
    primary: false,
    description: 'Practical skills at home and social-emotional growth.',
  },
  {
    id: 'creativity',
    name: 'Creativity',
    childName: 'Imagination Studio',
    color: '#d0679d',
    primary: false,
    description: 'Visual art, making, music and original storytelling.',
  },
];

export const STRANDS: Strand[] = [
  { id: 'reading.foundations', domainId: 'reading', name: 'Foundational Skills', description: 'Print concepts, phonics and fluency.' },
  {
    id: 'reading.comprehension',
    domainId: 'reading',
    name: 'Literature Comprehension',
    description: 'Understanding stories: details, characters, inference and theme.',
  },
  { id: 'reading.informational', domainId: 'reading', name: 'Informational Text', description: 'Reading to learn facts and follow procedures.' },
  { id: 'reading.oral', domainId: 'reading', name: 'Narration & Listening', description: 'Telling back and listening comprehension.' },
  { id: 'vocab.words', domainId: 'vocabulary', name: 'Word Knowledge', description: 'Meaning, relationships and precise word choice.' },
  { id: 'writing.handwriting', domainId: 'writing', name: 'Handwriting & Spelling', description: 'Letter formation and phonetic spelling.' },
  { id: 'writing.composition', domainId: 'writing', name: 'Composition', description: 'Expressing ideas through drawing, dictation and writing.' },
  { id: 'math.counting', domainId: 'math', name: 'Counting & Cardinality', description: 'Number names, counting and comparing quantities.' },
  { id: 'math.operations', domainId: 'math', name: 'Operations & Algebraic Thinking', description: 'Addition, subtraction, equal groups.' },
  { id: 'math.baseTen', domainId: 'math', name: 'Number & Operations in Base Ten', description: 'Place value: tens and ones.' },
  { id: 'math.measurement', domainId: 'math', name: 'Measurement & Data', description: 'Measuring, time, money and data.' },
  { id: 'math.geometry', domainId: 'math', name: 'Geometry & Patterns', description: 'Shapes, equal shares and patterns.' },
  {
    id: 'sci.practices',
    domainId: 'science',
    name: 'Science & Engineering Practices',
    description: 'Observing, questioning, predicting, explaining, designing.',
  },
  { id: 'sci.life', domainId: 'science', name: 'Life Science', description: 'Plants, animals, life cycles, habitats and fossils.' },
  { id: 'sci.physical', domainId: 'science', name: 'Physical Science', description: 'Materials, changes, forces, sound and light.' },
  { id: 'sci.earthSpace', domainId: 'science', name: 'Earth & Space Science', description: 'Sky patterns, weather and earth materials.' },
  { id: 'reason.logic', domainId: 'reasoning', name: 'Logic & Problem Solving', description: 'Sequencing, sorting, cause and effect, persistence.' },
  { id: 'life.home', domainId: 'lifeSkills', name: 'Home & Practical Life', description: 'Cooking, chores and self-care.' },
  { id: 'life.social', domainId: 'lifeSkills', name: 'Social-Emotional Learning', description: 'Feelings, empathy and sharing.' },
  { id: 'create.art', domainId: 'creativity', name: 'Visual Art & Making', description: 'Drawing, painting and building.' },
  { id: 'create.performing', domainId: 'creativity', name: 'Music & Storytelling', description: 'Music, rhythm and original stories.' },
];

const ela = (code: string, description: string): StandardRef => ({ framework: 'CCSS-ELA', code, description });
const mth = (code: string, description: string): StandardRef => ({ framework: 'CCSS-M', code, description });
const ngss = (code: string, description: string): StandardRef => ({ framework: 'NGSS', code, description });
const dci = (code: string, description: string): StandardRef => ({ framework: 'NGSS-DCI', code, description });
const arts = (code: string, description: string): StandardRef => ({ framework: 'NCAS', code, description });
const casel = (code: string, description: string): StandardRef => ({ framework: 'CASEL', code, description });
const elof = (code: string, description: string): StandardRef => ({ framework: 'ELOF', code, description });
const family = (description: string): StandardRef => ({ framework: 'Family', code: 'Family', description });

interface SkillInput {
  strand: string;
  name: string;
  can: string;
  childName: string;
  difficulty: Difficulty;
  prereq?: string[];
  standards: StandardRef[];
  topics?: string[];
  lessons?: string[];
  idea: string;
}

function defineSkills(input: Record<string, SkillInput>): Skill[] {
  return Object.entries(input).map(([id, s]) => {
    const strand = STRANDS.find((st) => st.id === s.strand);
    if (!strand) throw new Error(`Unknown strand ${s.strand} for ${id}`);
    return {
      id,
      strandId: s.strand,
      domainId: strand.domainId as DomainId,
      name: s.name,
      can: s.can,
      childName: s.childName,
      difficulty: s.difficulty,
      prerequisites: s.prereq ?? [],
      standards: s.standards,
      topics: s.topics ?? [],
      lessonIds: s.lessons ?? [],
      activityIdea: s.idea,
    };
  });
}

export const SKILLS: Skill[] = defineSkills({
  'reason.keyboard-match': {
    strand: 'reason.logic',
    name: 'Letter and keyboard matching',
    can: 'match a prompted Latin letter to its physical keyboard key',
    childName: 'Keyboard Explorer',
    difficulty: 0,
    standards: [
      { framework: 'Family', code: 'keyboard-letter-matching', description: 'Practice letter/key familiarity without implying reading or typing mastery.' },
    ],
    lessons: ['keyboard-trail'],
    idea: 'Find a prompted letter on a physical keyboard, without time pressure.',
  },
  'reason.letter-match': {
    strand: 'reason.logic',
    name: 'Letter recognition by touch',
    can: 'choose a matching Latin letter from labeled touch choices',
    childName: 'Letter Explorer',
    difficulty: 0,
    standards: [
      { framework: 'Family', code: 'keyboard-letter-matching', description: 'Practice letter/key familiarity without implying reading or typing mastery.' },
    ],
    lessons: ['keyboard-trail'],
    idea: 'Match a prompted letter by tapping a labeled letter choice.',
  },
  // ── Reading: foundations ────────────────────────────────────────────────
  'read.print-concepts': {
    strand: 'reading.foundations',
    name: 'Print concepts',
    can: 'track print and name a book’s title and author',
    childName: 'Book Explorer',
    difficulty: 0,
    standards: [ela('RF.K.1', 'Demonstrate understanding of the organization and basic features of print.')],
    idea: 'Point to the title and author on the next library book and ask who made it.',
  },
  'read.letter-sounds': {
    strand: 'reading.foundations',
    name: 'Letter–sound correspondence',
    can: 'match letters to their most common sounds',
    childName: 'Sound Detective',
    difficulty: 1,
    prereq: ['read.print-concepts'],
    standards: [ela('RF.K.3a', 'Demonstrate basic knowledge of one-to-one letter-sound correspondences.')],
    idea: 'Play “I spy something that starts with /m/” around the house.',
  },
  'read.decode-cvc': {
    strand: 'reading.foundations',
    name: 'Decoding simple words',
    can: 'decode consonant-vowel-consonant words',
    childName: 'Word Builder',
    difficulty: 1,
    prereq: ['read.letter-sounds'],
    standards: [ela('RF.K.3b', 'Associate long and short sounds with common spellings for the five major vowels.')],
    idea: 'Build words with magnet letters and swap one letter at a time (cat → hat → hot).',
  },
  'read.phonics-advanced': {
    strand: 'reading.foundations',
    name: 'Blends, digraphs & vowel teams',
    can: 'decode blends, digraphs and vowel teams',
    childName: 'Sound Mixer',
    difficulty: 3,
    prereq: ['read.decode-cvc'],
    standards: [
      ela('RF.1.3', 'Know and apply grade-level phonics and word analysis skills in decoding words.'),
      ela('RF.2.3b', 'Know spelling-sound correspondences for additional common vowel teams.'),
    ],
    idea: 'Hunt for “ai”, “ee” and “oa” words in a favorite picture book.',
  },
  'read.multisyllable': {
    strand: 'reading.foundations',
    name: 'Multisyllabic words',
    can: 'decode multisyllabic words',
    childName: 'Big Word Tamer',
    difficulty: 4,
    prereq: ['read.phonics-advanced'],
    standards: [ela('RF.3.3c', 'Decode multisyllable words.')],
    idea: 'Clap the syllables of long words from a chapter book, then read each part.',
  },
  'read.fluency': {
    strand: 'reading.foundations',
    name: 'Fluency & expression',
    can: 'read connected text accurately with expression',
    childName: 'Storyteller Voice',
    difficulty: 4,
    prereq: ['read.phonics-advanced'],
    standards: [ela('RF.3.4', 'Read with sufficient accuracy and fluency to support comprehension.')],
    idea: 'Record her reading a page in “character voices” and listen back together.',
  },
  // ── Reading: comprehension ──────────────────────────────────────────────
  'read.key-details': {
    strand: 'reading.comprehension',
    name: 'Key details',
    can: 'answer who, what, where and when questions about a story',
    childName: 'Story Spotter',
    difficulty: 2,
    prereq: ['read.print-concepts'],
    standards: [ela('RL.2.1', 'Ask and answer such questions as who, what, where, when, why, and how.')],
    lessons: ['story-chat'],
    idea: 'After reading, ask her to quiz you with three questions about the story.',
  },
  'read.characters': {
    strand: 'reading.comprehension',
    name: 'Characters, setting & events',
    can: 'describe characters, settings and major events',
    childName: 'Character Friend',
    difficulty: 2,
    prereq: ['read.key-details'],
    standards: [ela('RL.1.3', 'Describe characters, settings, and major events in a story, using key details.')],
    lessons: ['story-chat'],
    idea: 'Draw the setting of the book together and label where things happened.',
  },
  'read.retell': {
    strand: 'reading.comprehension',
    name: 'Retelling in sequence',
    can: 'retell a story’s beginning, middle and end',
    childName: 'Story Retold',
    difficulty: 2,
    prereq: ['read.key-details'],
    standards: [ela('RL.2.2', 'Recount stories and determine their central message, lesson, or moral.')],
    lessons: ['story-chat'],
    topics: [],
    idea: 'Use three sticky notes — beginning, middle, end — and have her narrate each.',
  },
  'read.feelings': {
    strand: 'reading.comprehension',
    name: 'Character feelings & motives',
    can: 'explain how characters feel and why',
    childName: 'Heart Reader',
    difficulty: 4,
    prereq: ['read.characters'],
    standards: [ela('RL.3.3', 'Describe characters in a story (traits, motivations, or feelings) and explain how their actions contribute to events.')],
    lessons: ['story-chat'],
    idea: 'Pause mid-chapter: “How is the character feeling right now? What makes you think so?”',
  },
  'read.inference': {
    strand: 'reading.comprehension',
    name: 'Inference',
    can: 'make inferences using clues from the text',
    childName: 'Clue Finder',
    difficulty: 4,
    prereq: ['read.characters'],
    standards: [
      ela('RL.3.1', 'Ask and answer questions to demonstrate understanding, referring explicitly to the text.'),
      ela('RL.4.1', 'Refer to details and examples in a text when drawing inferences.'),
    ],
    lessons: ['story-chat'],
    idea: 'Ask “why do you think…?” questions whose answers aren’t written on the page.',
  },
  'read.theme': {
    strand: 'reading.comprehension',
    name: 'Lesson or central message',
    can: 'identify a story’s lesson or central message',
    childName: 'Big Idea Finder',
    difficulty: 4,
    prereq: ['read.retell'],
    standards: [ela('RL.3.2', 'Recount stories, including fables; determine the central message, lesson, or moral.')],
    lessons: ['story-chat'],
    idea: 'Read a short fable and ask what the animals learned.',
  },
  'read.chapter-stamina': {
    strand: 'reading.comprehension',
    name: 'Chapter-book stamina',
    can: 'follow a story across multiple chapters and sittings',
    childName: 'Chapter Champion',
    difficulty: 4,
    prereq: ['read.retell'],
    standards: [ela('RL.3.10', 'Read and comprehend literature at the high end of the grades 2–3 text complexity band.')],
    lessons: ['story-chat'],
    idea: 'Before each chapter, have her recap where the story left off.',
  },
  'read.info-text': {
    strand: 'reading.informational',
    name: 'Reading for facts',
    can: 'find key facts in informational text',
    childName: 'Fact Finder',
    difficulty: 2,
    prereq: ['read.key-details'],
    standards: [ela('RI.2.1', 'Ask and answer questions to demonstrate understanding of key details in a text.')],
    idea: 'Read a nonfiction animal book and make a “3 facts I learned” card.',
  },
  'read.procedural': {
    strand: 'reading.informational',
    name: 'Following written steps',
    can: 'read and follow multi-step written directions',
    childName: 'Recipe Reader',
    difficulty: 3,
    prereq: ['read.info-text'],
    standards: [ela('RI.3.3', 'Describe the relationship between a series of steps in technical procedures.')],
    idea: 'Let her read a recipe aloud, one step at a time, while you cook together.',
  },
  'read.narration': {
    strand: 'reading.oral',
    name: 'Oral narration',
    can: 'tell back what was read in her own words',
    childName: 'Tell-It-Back',
    difficulty: 1,
    standards: [ela('SL.2.2', 'Recount or describe key ideas or details from a text read aloud.')],
    lessons: ['story-chat'],
    idea: 'After a read-aloud, ask “Tell me everything you remember.” Write down her words.',
  },
  'read.listening': {
    strand: 'reading.oral',
    name: 'Listening comprehension',
    can: 'understand and discuss stories read aloud',
    childName: 'Good Listener',
    difficulty: 0,
    standards: [ela('SL.K.2', 'Confirm understanding of a text read aloud by asking and answering questions.')],
    idea: 'Read aloud a book above her reading level and talk about it together.',
  },
  // ── Vocabulary ──────────────────────────────────────────────────────────
  'vocab.context': {
    strand: 'vocab.words',
    name: 'Words from context',
    can: 'use context clues to work out new words',
    childName: 'Word Sleuth',
    difficulty: 3,
    prereq: ['read.key-details'],
    standards: [ela('L.3.4a', 'Use sentence-level context as a clue to the meaning of a word or phrase.')],
    lessons: ['story-chat'],
    idea: 'When she meets a new word, ask her to guess its meaning from the sentence first.',
  },
  'vocab.rich-words': {
    strand: 'vocab.words',
    name: 'Rich, precise words',
    can: 'use rich and precise words in speech',
    childName: 'Word Collector',
    difficulty: 1,
    standards: [ela('L.K.6', 'Use words and phrases acquired through conversations, reading and being read to.')],
    idea: 'Keep a “fancy words” jar — add a word each time she uses a new one.',
  },
  'vocab.relationships': {
    strand: 'vocab.words',
    name: 'Word relationships',
    can: 'sort words by category, opposites and shades of meaning',
    childName: 'Word Sorter',
    difficulty: 1,
    standards: [ela('L.K.5', 'With guidance, explore word relationships and nuances in word meanings.')],
    idea: 'Line up “warm, hot, boiling” and act out the differences.',
  },
  'vocab.domain': {
    strand: 'vocab.words',
    name: 'Subject vocabulary',
    can: 'use science and math words accurately',
    childName: 'Expert Words',
    difficulty: 3,
    standards: [ela('L.3.6', 'Acquire and use accurately grade-appropriate general academic and domain-specific words.')],
    idea: 'Introduce one “scientist word” per experiment (predict, observe, dissolve).',
  },
  // ── Writing ─────────────────────────────────────────────────────────────
  'write.name': {
    strand: 'writing.handwriting',
    name: 'Writing her name',
    can: 'write her own name',
    childName: 'My Name',
    difficulty: 0,
    standards: [elof('P-LIT 6', 'Child writes for a variety of purposes using increasingly sophisticated marks.')],
    idea: 'Sign every piece of artwork together.',
  },
  'write.letters': {
    strand: 'writing.handwriting',
    name: 'Letter formation',
    can: 'form upper- and lowercase letters',
    childName: 'Letter Maker',
    difficulty: 1,
    prereq: ['write.name'],
    standards: [ela('L.K.1a', 'Print many upper- and lowercase letters.')],
    idea: 'Trace letters in a tray of salt or shaving cream.',
  },
  'write.spelling': {
    strand: 'writing.handwriting',
    name: 'Phonetic spelling',
    can: 'spell simple words by their sounds',
    childName: 'Sound Speller',
    difficulty: 1,
    prereq: ['read.letter-sounds'],
    standards: [ela('L.K.2d', 'Spell simple words phonetically, drawing on letter-sound relationships.')],
    idea: 'Label drawings with sound-spelled words — celebrate her spellings.',
  },
  'write.composing': {
    strand: 'writing.composition',
    name: 'Composing ideas',
    can: 'compose ideas by drawing, dictating and writing',
    childName: 'Idea Writer',
    difficulty: 1,
    standards: [ela('W.K.2', 'Use drawing, dictating, and writing to compose informative texts.')],
    idea: 'Have her dictate a letter to a grandparent while you scribe.',
  },
  'write.sentences': {
    strand: 'writing.composition',
    name: 'Complete sentences',
    can: 'write complete sentences',
    childName: 'Sentence Star',
    difficulty: 2,
    prereq: ['write.letters', 'write.spelling'],
    standards: [ela('W.1.2', 'Write informative/explanatory texts naming a topic and supplying facts.')],
    idea: 'Write one sentence caption for each nature-walk photo.',
  },
  // ── Math: counting ──────────────────────────────────────────────────────
  'math.count-10': {
    strand: 'math.counting',
    name: 'Counting to 10',
    can: 'count up to 10 objects with one-to-one correspondence',
    childName: 'Counting Stars',
    difficulty: 0,
    standards: [mth('K.CC.B.4', 'Understand the relationship between numbers and quantities; connect counting to cardinality.')],
    lessons: ['moon-rocks'],
    idea: 'Count out snacks, stairs and socks.',
  },
  'math.count-20': {
    strand: 'math.counting',
    name: 'Counting to 20',
    can: 'count to tell how many, up to 20 objects',
    childName: 'Counting Comets',
    difficulty: 1,
    prereq: ['math.count-10'],
    standards: [mth('K.CC.B.5', 'Count to answer “how many?” questions about as many as 20 things.')],
    lessons: ['moon-rocks'],
    idea: 'Count muffin cups, buttons or blocks into groups of 20.',
  },
  'math.count-100': {
    strand: 'math.counting',
    name: 'Counting to 100',
    can: 'count to 100 by ones and by tens',
    childName: 'Hundred Hiker',
    difficulty: 1,
    prereq: ['math.count-20'],
    standards: [mth('K.CC.A.1', 'Count to 100 by ones and by tens.')],
    idea: 'Celebrate the 100th day — collect 100 small things in ten groups of ten.',
  },
  'math.compare': {
    strand: 'math.counting',
    name: 'Comparing groups',
    can: 'compare two groups as more, fewer or equal',
    childName: 'More or Less',
    difficulty: 1,
    prereq: ['math.count-10'],
    standards: [mth('K.CC.C.6', 'Identify whether the number of objects in one group is greater than, less than, or equal to another.')],
    lessons: ['moon-rocks'],
    idea: 'Deal out two piles of cards and ask which has more.',
  },
  'math.numerals': {
    strand: 'math.counting',
    name: 'Reading & writing numerals',
    can: 'read and write numerals 0–20',
    childName: 'Number Writer',
    difficulty: 1,
    prereq: ['math.count-10'],
    standards: [mth('K.CC.A.3', 'Write numbers from 0 to 20.')],
    idea: 'Write house numbers and prices you see on a walk.',
  },
  // ── Math: operations ────────────────────────────────────────────────────
  'math.add-10': {
    strand: 'math.operations',
    name: 'Adding within 10',
    can: 'add within 10',
    childName: 'Plus Power',
    difficulty: 1,
    prereq: ['math.count-10'],
    standards: [mth('K.OA.A.2', 'Solve addition and subtraction word problems, and add and subtract within 10.')],
    lessons: ['moon-rocks'],
    idea: 'Two hands, ten fingers: show “3 and 4 more” with fingers.',
  },
  'math.sub-10': {
    strand: 'math.operations',
    name: 'Subtracting within 10',
    can: 'subtract within 10',
    childName: 'Take-Away Trail',
    difficulty: 1,
    prereq: ['math.count-10'],
    standards: [mth('K.OA.A.2', 'Solve addition and subtraction word problems, and add and subtract within 10.')],
    lessons: ['moon-rocks'],
    idea: 'Eat grapes one at a time: “We had 8, now how many?”',
  },
  'math.add-20': {
    strand: 'math.operations',
    name: 'Adding & subtracting within 20',
    can: 'add and subtract within 20',
    childName: 'Rocket Math',
    difficulty: 2,
    prereq: ['math.add-10', 'math.count-20'],
    standards: [mth('1.OA.C.6', 'Add and subtract within 20, demonstrating fluency for addition and subtraction within 10.')],
    lessons: ['moon-rocks'],
    idea: 'Use a 20-bead string to show “8 + 5” as “8 + 2 + 3”.',
  },
  'math.word-problems': {
    strand: 'math.operations',
    name: 'Word problems within 20',
    can: 'solve story problems within 20',
    childName: 'Story Sums',
    difficulty: 2,
    prereq: ['math.add-10'],
    standards: [mth('1.OA.A.1', 'Use addition and subtraction within 20 to solve word problems.')],
    lessons: ['moon-rocks'],
    idea: 'Make up story problems about her stuffed animals at a tea party.',
  },
  'math.equal-shares': {
    strand: 'math.operations',
    name: 'Equal sharing & even/odd',
    can: 'share a group equally and tell even from odd',
    childName: 'Fair Share',
    difficulty: 3,
    prereq: ['math.add-20'],
    standards: [mth('2.OA.C.3', 'Determine whether a group of objects (up to 20) has an odd or even number of members.')],
    lessons: ['moon-rocks'],
    idea: 'Share crackers fairly between two plates — is there one left over?',
  },
  'math.equal-groups': {
    strand: 'math.operations',
    name: 'Equal groups (early multiplication)',
    can: 'find totals of equal groups',
    childName: 'Group Galaxy',
    difficulty: 4,
    prereq: ['math.equal-shares'],
    standards: [
      mth('2.OA.C.4', 'Use addition to find the total number of objects arranged in rectangular arrays.'),
      mth('3.OA.A.1', 'Interpret products of whole numbers as groups of objects.'),
    ],
    lessons: ['moon-rocks'],
    idea: 'Arrange muffin tins as arrays: 3 rows of 4.',
  },
  'math.place-value': {
    strand: 'math.baseTen',
    name: 'Tens and ones',
    can: 'understand two-digit numbers as tens and ones',
    childName: 'Ten Towers',
    difficulty: 2,
    prereq: ['math.count-20'],
    standards: [mth('1.NBT.B.2', 'Understand that the two digits of a two-digit number represent amounts of tens and ones.')],
    idea: 'Bundle straws into tens with rubber bands.',
  },
  // ── Math: measurement & data ────────────────────────────────────────────
  'math.measure-compare': {
    strand: 'math.measurement',
    name: 'Comparing attributes',
    can: 'compare objects by length, weight and capacity',
    childName: 'Big & Small',
    difficulty: 1,
    standards: [mth('K.MD.A.2', 'Directly compare two objects with a measurable attribute in common.')],
    idea: 'Line up shoes from shortest to longest.',
  },
  'math.measure-units': {
    strand: 'math.measurement',
    name: 'Standard units',
    can: 'measure with standard units such as cups, spoons and inches',
    childName: 'Measure Master',
    difficulty: 3,
    prereq: ['math.measure-compare'],
    standards: [
      mth('2.MD.A.1', 'Measure the length of an object by selecting and using appropriate tools.'),
      mth('3.MD.A.2', 'Measure and estimate liquid volumes and masses of objects using standard units.'),
    ],
    idea: 'Let her measure every dry ingredient in the next recipe.',
  },
  'math.time': {
    strand: 'math.measurement',
    name: 'Telling time',
    can: 'tell time to the hour and half hour',
    childName: 'Clock Keeper',
    difficulty: 2,
    standards: [mth('1.MD.B.3', 'Tell and write time in hours and half-hours using analog and digital clocks.')],
    idea: 'Put a paper clock on the fridge showing snack time.',
  },
  'math.money': {
    strand: 'math.measurement',
    name: 'Coins & money',
    can: 'identify coins and count small amounts of money',
    childName: 'Coin Counter',
    difficulty: 3,
    prereq: ['math.count-100'],
    standards: [mth('2.MD.C.8', 'Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies.')],
    idea: 'Play store with real coins and price tags under 20¢.',
  },
  'math.data': {
    strand: 'math.measurement',
    name: 'Sorting & counting data',
    can: 'sort objects into categories and count each group',
    childName: 'Sort & Count',
    difficulty: 1,
    standards: [mth('K.MD.B.3', 'Classify objects into given categories; count the numbers of objects in each category.')],
    idea: 'Sort a nature-walk collection by type and make a tally chart.',
  },
  // ── Math: geometry & patterns ───────────────────────────────────────────
  'math.shapes': {
    strand: 'math.geometry',
    name: 'Naming shapes',
    can: 'name 2D and 3D shapes regardless of size or orientation',
    childName: 'Shape Spotter',
    difficulty: 1,
    standards: [mth('K.G.A.2', 'Correctly name shapes regardless of their orientations or overall size.')],
    idea: 'Go on a shape hunt: find five circles and three cylinders at home.',
  },
  'math.fractions': {
    strand: 'math.geometry',
    name: 'Halves & fourths',
    can: 'partition shapes into halves and fourths',
    childName: 'Fair Slices',
    difficulty: 2,
    prereq: ['math.shapes'],
    standards: [mth('1.G.A.3', 'Partition circles and rectangles into two and four equal shares.')],
    idea: 'Cut sandwiches and pancakes into halves and fourths.',
  },
  'math.patterns': {
    strand: 'math.geometry',
    name: 'Patterns',
    can: 'recognize, extend and create patterns',
    childName: 'Pattern Parade',
    difficulty: 0,
    standards: [elof('P-MATH 9', 'Child recognizes, duplicates, and extends simple patterns.')],
    idea: 'Make bead necklaces in AB and ABC patterns.',
  },
  // ── Science: practices ──────────────────────────────────────────────────
  'sci.observe': {
    strand: 'sci.practices',
    name: 'Careful observation',
    can: 'make careful, detailed observations',
    childName: 'Keen Eyes',
    difficulty: 0,
    standards: [ngss('K-2 SEP-3', 'Planning and carrying out investigations: make observations to collect data.')],
    lessons: ['sink-float'],
    idea: 'Use a magnifying glass to draw a leaf in detail.',
  },
  'sci.questions': {
    strand: 'sci.practices',
    name: 'Asking questions',
    can: 'ask questions about how and why things happen',
    childName: 'Why Wonderer',
    difficulty: 0,
    standards: [ngss('K-2 SEP-1', 'Asking questions based on observations to find more information about the world.')],
    idea: 'Start a “wonder wall” of her questions and investigate one each week.',
  },
  'sci.predict': {
    strand: 'sci.practices',
    name: 'Predicting & testing',
    can: 'make predictions and test them',
    childName: 'Guess & Test',
    difficulty: 1,
    prereq: ['sci.observe'],
    standards: [ngss('K-2 SEP-3', 'Make predictions based on prior experiences.')],
    lessons: ['sink-float'],
    idea: 'Before every experiment, write down her prediction first.',
  },
  'sci.explain': {
    strand: 'sci.practices',
    name: 'Explaining with evidence',
    can: 'explain results using evidence',
    childName: 'Because Builder',
    difficulty: 2,
    prereq: ['sci.predict'],
    standards: [ngss('K-2 SEP-6', 'Constructing explanations: use evidence to support an account of a phenomenon.')],
    lessons: ['sink-float'],
    idea: 'Ask “How do you know?” after she states a result.',
  },
  'sci.engineer': {
    strand: 'sci.practices',
    name: 'Designing & building',
    can: 'design and build something to solve a problem',
    childName: 'Little Engineer',
    difficulty: 1,
    standards: [ngss('K-2-ETS1-2', 'Develop a simple sketch, drawing, or physical model to illustrate how the shape of an object helps it function.')],
    idea: 'Build a bridge from blocks that holds a toy car.',
  },
  // ── Science: life ───────────────────────────────────────────────────────
  'sci.plants': {
    strand: 'sci.life',
    name: 'What plants need',
    can: 'explain what plants need to live and grow',
    childName: 'Green Thumb',
    difficulty: 1,
    topics: ['plants'],
    standards: [
      ngss('K-LS1-1', 'Describe patterns of what plants and animals need to survive.'),
      ngss('2-LS2-1', 'Plan and conduct an investigation to determine if plants need sunlight and water to grow.'),
    ],
    idea: 'Grow two bean sprouts — one in a dark cupboard — and compare.',
  },
  'sci.animals': {
    strand: 'sci.life',
    name: 'Animals & their needs',
    can: 'describe what animals need and how they live',
    childName: 'Animal Friend',
    difficulty: 1,
    topics: ['animals'],
    standards: [ngss('K-LS1-1', 'Describe patterns of what plants and animals need to survive.')],
    idea: 'Watch birds at a feeder and record what they eat.',
  },
  'sci.life-cycles': {
    strand: 'sci.life',
    name: 'Life cycles & growth',
    can: 'describe how living things grow and change',
    childName: 'Growing Up',
    difficulty: 2,
    topics: ['animals', 'plants'],
    standards: [
      ngss('1-LS3-1', 'Young plants and animals are like, but not exactly like, their parents.'),
      ngss('3-LS1-1', 'Organisms have unique and diverse life cycles.'),
    ],
    idea: 'Raise caterpillars or tadpoles and draw each stage.',
  },
  'sci.habitats': {
    strand: 'sci.life',
    name: 'Habitats & diversity',
    can: 'compare living things in different habitats',
    childName: 'Habitat Hunter',
    difficulty: 3,
    topics: ['nature'],
    standards: [ngss('2-LS4-1', 'Make observations of plants and animals to compare the diversity of life in different habitats.')],
    idea: 'Count different living things in a hula-hoop patch of lawn vs. woods.',
  },
  'sci.fossils': {
    strand: 'sci.life',
    name: 'Fossils & dinosaurs',
    can: 'explain what fossils tell us about life long ago',
    childName: 'Fossil Finder',
    difficulty: 4,
    topics: ['dinosaurs'],
    standards: [ngss('3-LS4-1', 'Analyze fossils to provide evidence of the organisms and environments of long ago.')],
    idea: 'Press shells into playdough to make “fossils,” then dig them up.',
  },
  // ── Science: physical ───────────────────────────────────────────────────
  'sci.materials': {
    strand: 'sci.physical',
    name: 'Properties of materials',
    can: 'classify materials by observable properties (like sinking and floating)',
    childName: 'Material Magician',
    difficulty: 3,
    prereq: ['sci.observe'],
    standards: [ngss('2-PS1-1', 'Plan and conduct an investigation to describe and classify materials by their observable properties.')],
    lessons: ['sink-float'],
    topics: ['water'],
    idea: 'Sort bath toys into sinkers and floaters, then ask why.',
  },
  'sci.changes': {
    strand: 'sci.physical',
    name: 'Heating & cooling changes',
    can: 'explain how heating or cooling changes materials',
    childName: 'Kitchen Chemist',
    difficulty: 3,
    standards: [ngss('2-PS1-4', 'Construct an argument that some changes caused by heating or cooling can be reversed and some cannot.')],
    idea: 'Melt chocolate and let it re-harden; bake a muffin and ask if it can go back.',
  },
  'sci.forces': {
    strand: 'sci.physical',
    name: 'Pushes & pulls',
    can: 'describe how pushes and pulls change motion',
    childName: 'Push & Pull',
    difficulty: 1,
    standards: [ngss('K-PS2-1', 'Compare the effects of different strengths or directions of pushes and pulls.')],
    idea: 'Roll balls down ramps of different heights.',
  },
  'sci.sound-light': {
    strand: 'sci.physical',
    name: 'Sound & light',
    can: 'explain that sound comes from vibration and light lets us see',
    childName: 'Buzz & Glow',
    difficulty: 2,
    standards: [ngss('1-PS4-1', 'Plan and conduct investigations that vibrating materials can make sound.')],
    idea: 'Make a rubber-band guitar and a shadow puppet show.',
  },
  // ── Science: earth & space ──────────────────────────────────────────────
  'sci.sky': {
    strand: 'sci.earthSpace',
    name: 'Sun, moon & stars',
    can: 'describe patterns of the sun, moon and stars',
    childName: 'Star Gazer',
    difficulty: 2,
    topics: ['space'],
    standards: [ngss('1-ESS1-1', 'Use observations of the sun, moon, and stars to describe patterns that can be predicted.')],
    idea: 'Draw the moon every clear night for two weeks.',
  },
  'sci.weather': {
    strand: 'sci.earthSpace',
    name: 'Weather & seasons',
    can: 'describe weather patterns and seasons',
    childName: 'Weather Watcher',
    difficulty: 1,
    standards: [ngss('K-ESS2-1', 'Use and share observations of local weather conditions to describe patterns over time.')],
    idea: 'Keep a weather chart by the window for a month.',
  },
  'sci.earth-materials': {
    strand: 'sci.earthSpace',
    name: 'Rocks, soil & water',
    can: 'describe rocks, soil and other earth materials',
    childName: 'Rock Hound',
    difficulty: 2,
    topics: ['nature'],
    standards: [dci('ESS2.A', 'Earth materials and systems: wind and water change the shape of the land.')],
    idea: 'Start a rock collection sorted by color, texture and size.',
  },
  // ── Reasoning ───────────────────────────────────────────────────────────
  'reason.sequencing': {
    strand: 'reason.logic',
    name: 'Sequencing',
    can: 'put events and steps in order',
    childName: 'First, Next, Last',
    difficulty: 0,
    standards: [elof('P-LC 4', 'Child understands and uses sequence words to describe events.')],
    idea: 'Photograph steps of a craft and have her order the photos.',
  },
  'reason.classifying': {
    strand: 'reason.logic',
    name: 'Classifying by attributes',
    can: 'sort by more than one attribute and explain the rule',
    childName: 'Sorting Sorter',
    difficulty: 1,
    standards: [mth('K.MD.B.3', 'Classify objects into given categories.')],
    idea: 'Sort buttons by color, then re-sort by number of holes.',
  },
  'reason.cause-effect': {
    strand: 'reason.logic',
    name: 'Cause & effect',
    can: 'explain cause and effect relationships',
    childName: 'What Happens If',
    difficulty: 2,
    standards: [ela('RI.3.3', 'Describe the relationship between events using language that pertains to time, sequence, and cause/effect.')],
    idea: 'Ask “what would happen if…?” questions during everyday tasks.',
  },
  'reason.persistence': {
    strand: 'reason.logic',
    name: 'Persistence in problem solving',
    can: 'try different strategies and keep going on hard problems',
    childName: 'Never-Give-Up',
    difficulty: 1,
    standards: [{ framework: 'CCSS-MP', code: 'MP1', description: 'Make sense of problems and persevere in solving them.' }],
    lessons: ['moon-rocks'],
    idea: 'Do a slightly-too-hard puzzle together and name the strategies she tries.',
  },
  // ── Life skills ─────────────────────────────────────────────────────────
  'life.cooking': {
    strand: 'life.home',
    name: 'Cooking & kitchen helping',
    can: 'help prepare food safely',
    childName: 'Kitchen Helper',
    difficulty: 0,
    standards: [family('Practical life: food preparation and kitchen safety.')],
    idea: 'Give her a real job in every meal: washing, stirring or measuring.',
  },
  'life.chores': {
    strand: 'life.home',
    name: 'Household contributions',
    can: 'complete simple household tasks',
    childName: 'Home Hero',
    difficulty: 0,
    standards: [family('Practical life: contributing to the household.')],
    idea: 'Make a picture checklist for tidying her room.',
  },
  'life.self-care': {
    strand: 'life.home',
    name: 'Self-care',
    can: 'dress, tidy and care for herself',
    childName: 'I Can Do It',
    difficulty: 0,
    standards: [elof('P-PMP 3', 'Child demonstrates personal care and hygiene skills.')],
    idea: 'Let her choose and put on her outfit independently.',
  },
  'life.emotions': {
    strand: 'life.social',
    name: 'Naming & managing feelings',
    can: 'name feelings and use calming strategies',
    childName: 'Feelings Explorer',
    difficulty: 0,
    standards: [casel('Self-awareness', 'Identifying one’s emotions and managing them.')],
    idea: 'Use a feelings chart at bedtime to talk about the day.',
  },
  'life.kindness': {
    strand: 'life.social',
    name: 'Empathy & kindness',
    can: 'notice others’ feelings and help',
    childName: 'Kind Heart',
    difficulty: 0,
    standards: [casel('Social awareness', 'Taking others’ perspectives and showing concern for their feelings.')],
    idea: 'Make a card for a neighbor or grandparent.',
  },
  'life.money-sense': {
    strand: 'life.social',
    name: 'Buying, saving & sharing',
    can: 'understand buying, saving and sharing money',
    childName: 'Piggy Bank Pro',
    difficulty: 1,
    standards: [family('Financial literacy: needs vs. wants, saving and giving.')],
    idea: 'Use three jars — save, spend, share — for any coins she receives.',
  },
  // ── Creativity ──────────────────────────────────────────────────────────
  'art.drawing': {
    strand: 'create.art',
    name: 'Drawing & painting',
    can: 'draw and paint to express ideas',
    childName: 'Little Artist',
    difficulty: 0,
    topics: ['art'],
    standards: [arts('VA:Cr1.1.K', 'Engage in exploration and imaginative play with materials.')],
    idea: 'Paint what she sees out the window with watercolors.',
  },
  'art.color': {
    strand: 'create.art',
    name: 'Color & materials',
    can: 'explore color mixing and art materials',
    childName: 'Color Wizard',
    difficulty: 0,
    topics: ['art'],
    standards: [arts('VA:Cr2.1.K', 'Through experimentation, build skills in various media and approaches to art-making.')],
    idea: 'Mix primary colors in muffin tins and name the new colors.',
  },
  'art.making': {
    strand: 'create.art',
    name: 'Building & crafting',
    can: 'build and craft three-dimensional art',
    childName: 'Maker Hands',
    difficulty: 1,
    topics: ['art'],
    standards: [arts('VA:Cr2.1.1', 'Explore uses of materials and tools to create works of art or design.')],
    idea: 'Build a cardboard-box castle and decorate it.',
  },
  'art.music': {
    strand: 'create.performing',
    name: 'Music & rhythm',
    can: 'sing, keep a steady beat and explore instruments',
    childName: 'Music Maker',
    difficulty: 0,
    standards: [arts('MU:Pr4.2.K', 'Explore music’s expressive qualities (such as voice quality, dynamics and tempo).')],
    idea: 'Play pots-and-pans drums along to a favorite song.',
  },
  'art.storytelling': {
    strand: 'create.performing',
    name: 'Original storytelling',
    can: 'invent and tell original stories',
    childName: 'Story Maker',
    difficulty: 1,
    standards: [ela('W.K.3', 'Use drawing, dictating, and writing to narrate a sequence of events.')],
    idea: 'Take turns adding one sentence to a silly bedtime story.',
  },
});
